# Generated by Django 4.0.3 on 2023-10-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_finedust_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CITY_FINEDUST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('seoul', models.FloatField()),
                ('busan', models.FloatField()),
                ('daegu', models.FloatField()),
                ('incheon', models.FloatField()),
                ('gwangju', models.FloatField()),
                ('daejeon', models.FloatField()),
                ('ulsan', models.FloatField()),
                ('sejong', models.FloatField()),
                ('gyeonggi', models.FloatField()),
                ('gangwon', models.FloatField()),
                ('chungbuk', models.FloatField()),
                ('chungnam', models.FloatField()),
                ('jeonbuk', models.FloatField()),
                ('jeonnam', models.FloatField()),
                ('gyeongbuk', models.FloatField()),
                ('gyeongnam', models.FloatField()),
                ('jeju', models.FloatField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
