# Generated by Django 4.0.3 on 2023-10-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_finedust'),
    ]

    operations = [
        migrations.CreateModel(
            name='NUM_NEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('num_news', models.IntegerField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
