# Generated by Django 4.0.3 on 2023-10-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_station_location2'),
    ]

    operations = [
        migrations.CreateModel(
            name='NURAK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('addr', models.CharField(max_length=250)),
            ],
        ),
    ]
