# Generated by Django 4.0.3 on 2023-10-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nurak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurak',
            options={'ordering': ('name',)},
        ),
    ]
